'use client';

import '../styles/global.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '../components/header';
import { Footer } from '@/components/footer';
import { ReduxProvider } from '@/redux/provider';
import Search from '@/components/search';

const inter = Inter({ subsets: ['latin'] });

/*export const metadata: Metadata = {
	title: 'Timesprint',
	description: 'Generated by create next app',
};*/

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReduxProvider>
					<Search />
					<Header />
					{children}
					<Footer />
				</ReduxProvider>
			</body>
		</html>
	);
}
