import '../styles/global.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ReduxProvider } from '@/redux/provider';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

/*export const metadata: Metadata = {
	title: 'Timesprint',
	description: 'Generated by create next app',
};*/

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
